import fs from 'node:fs';
import path from 'node:path';

import { cli, setupUncaughtExceptionHandler } from './cli';

setupUncaughtExceptionHandler();

/**
 * Programmatic entry point for data-package bin shims generated by `npmdata init`.
 *
 * @param binDir - The bin/ directory of the data package (__dirname from the shim).
 * @param args   - CLI arguments (without node + script, i.e. process.argv.slice(2)).
 */
export async function binpkg(binDir: string, args: string[]): Promise<void> {
  if (args.includes('--packages')) {
    // eslint-disable-next-line no-console
    console.log('Cannot use --packages when invoked from a data package bin shim');
    // eslint-disable-next-line unicorn/no-process-exit
    process.exit(1);
  }

  const pkgRootDir = path.join(binDir, '..');
  const pkgJson = JSON.parse(fs.readFileSync(path.join(pkgRootDir, 'package.json')).toString()) as {
    name: string;
  };
  const exitCode = await cli(
    ['node', 'npmdata', ...args, '--packages', pkgJson.name],
    process.cwd(),
    pkgRootDir,
  );
  // eslint-disable-next-line unicorn/no-process-exit
  process.exit(exitCode);
}
